### PR TITLE
Add file-based caching

### PR DESCRIPTION
**Pull request by khandelwal**
To improve the performance of our pages, let's add some view-based caching. We add file-based caching for simplicity.

### CODE REVIEW

**Comment by khandelwal** [comment]
@theresaanna Do these changes make sense to you? I'm trying to add simple file-based caching to the application. This was pretty successful when I did this with openFOIA.

**Comment by cmc333333** [comment]
Any reason not to use a [site-wide cache](https://docs.djangoproject.com/en/1.8/topics/cache/#the-per-site-cache)?

**Comment by khandelwal** [comment]
Here's my reasoning: it's not a read-only site. There are at least a couple instances in which we generate individualized views (we're issuing vouchers with barcodes on them). I thought doing site-wide cache would mean that those pages would get cached (they don't have individualized URLs) which doesn't work. 

Doing it view by view seems to offer a little more control. 

Am I confused about how the site-wide cache works?

**Comment by dlapiduz** [comment]
@cmc333333 I think site-wide cache is intended for sites that are either mostly static or have a low refresh rate... if you have individualized views as @khandelwal says it makes sense to have some finer control on what you cache IMHO

**Comment by theresaanna** [comment]
My first thought was "can't you use decorators on the views instead of junking up `urls.py`?" Which, you can, though the docs don't seem to prefer that: 

> "This approach couples your view to the cache system, which is not ideal for several reasons. For instance, you might want to reuse the view functions on another, cache-less site, or you might want to distribute the views to people who might want to use them without being cached."

https://docs.djangoproject.com/en/1.8/topics/cache/#the-per-view-cache

Just an FYI, as I suspect that approach still has its place, I just don't know if its EKIP.

Everything looks looks good to me.

**Comment by khandelwal** [comment]
Yeah, I don't like putting this in urls.py either.

**Comment by dlapiduz** [comment]
@theresaanna that was my though too re: the code itself... :+1: to decorators

**Comment by cmc333333** [comment]
> There are at least a couple instances in which we generate individualized views (we're issuing vouchers with barcodes on them).

As long as you're getting to those pages via POST caching won't come into play. Similarly, if you are using GETs, as long as you have a unique query string, the cache won't be outdated. In general, the same url shouldn't generate different content.

**Comment by cmc333333** [comment]
> Yeah, I don't like putting this in urls.py either.

One thing you could consider is to add a wrapper decorator that determines whether or not to cache based on configuration. E.g. `secure_write` in https://github.com/18F/regulations-core/pull/15/files

Though, I suppose a dummy cache does exactly that.

**Comment by khandelwal** [comment]
I ran some load tests to check the impact of this. 

Before caching: 
Average response time: 1.06s
52% of requests timed out (1 second threshold)

After caching: 
Average response time: 190ms
No requests timed out (1 second threshold)

I think that's a pretty decent performance improvement (within the limited parameters of the test). 

Let's get this merged, and then we can see about refining some of the code.

**Comment by theresaanna** [comment]
@khandelwal friendly reminder to create the issue now re: refinements, so that you don't forget.

**Pull request merged**
