### PR TITLE
Fixes the EKIP logo sizing responsively between about 518px and 800px.

### PR DESCRIPTION
**Pull request by billygriffin**
Before:
screen shot 2016-06-06 at 10 13 46 am
After:
screen shot 2016-06-06 at 10 14 25 am

### CODE REVIEW

**Comment by billygriffin** [comment]
@khandelwal Just checking if anyone saw this. :)

**Comment by OpenGlobe** [comment]
Thanks @billy22g !  @cacraig do you mind taking a look at this when you have a free moment?  We can also ping @xtine for a look too.  Thanks for the contribution Billy.

**Comment by xtine** [comment]
Hi @billy22g, thanks for your contribution! This is a good fix, however the change should happen in `scss/_responsive.scss` file instead because the `style.css` file is actually compiled from the files in the scss directory.

Link to line in correct file: https://github.com/18F/ekip-api/blob/master/ekip/everykid/static/scss/_responsive.scss#L51

**Comment by OpenGlobe** [comment]
Thanks @xtine !

**Comment by billygriffin** [comment]
Thanks @xtine! The updated PR look ok to you?

And thanks @OpenGlobe as well!

**Comment by xtine** [comment]
@billy22g One last thing would be to run gulp command to compile it into the main `style.css` and it should be good to go. @OpenGlobe: what are the logistics to get the eventual merged PR pushed?

**Comment by billygriffin** [comment]
@xtine and @OpenGlobe: Should be good to go now. Pushed after running gulp and style.css looks like it compiled with the change incorporated. Sorry for the delay, and please let me know if there's anything else I can do to help!

Also, I'm starting at 18F next month, so excited to work more with both of you! :)

**Comment by billygriffin** [comment]
@OpenGlobe I think @xtine is good with this. Do you know how we get it deployed? Thanks to both of you!

**Comment by OpenGlobe** [comment]
Thanks for flagging @billy22g - @cacraig - mind taking a look when you have a moment?

**Comment by billygriffin** [comment]
@cacraig Sorry if this is annoying, just bumping in case you didn't see it. Thanks!

**Comment by billygriffin** [comment]
Hey @cacraig, did you have a chance to look at this? I think it's pretty straightforward but happy to make any changes needed if not. Thanks!

**Comment by cacraig** [comment]
Looks to me good. Merging. We'll get this deployed in a jiffy.

**Pull request merged**
