### PR TITLE
Load pass issuing federal sites data

### PR DESCRIPTION
**Pull request by khandelwal**
This sets up the models, and management commands to load the federal sites data. The dataset it loads is the list of all the federal parks, forests, etc. that issue versions of the annual park pass.

### CODE REVIEW

**Comment by khandelwal** [comment]
@xtine Another PR for you to review and merge.

**Comment by xtine** [comment]
Is there a way for me to run the tests locally?

**Comment by khandelwal** [comment]
Yeah. I run them like this: 
python manage.py test --settings=config.settings.test

**Comment by xtine** [comment]
Tests pass for me.

**Pull request merged**
