### PR TITLE
Authority to operate - please merge

### PR DESCRIPTION
**Pull request by NoahKunin**
:shipit: Ready to Merge :shipit: 

This PR represents the system's ATO.

### CODE REVIEW

**Comment by khandelwal** [comment]
This is pretty fantastic - how this is being done.

**Comment by NoahKunin** [comment]
@khandelwal just wait until we start GitBook-ing it too

**Comment by NoahKunin** [comment]
@khandelwal while in general I always default to deleting branches too after PR, I'd like the `authority-to-operate` branch to stay. Part of my vision is that every repo have an ATO branch, so there is always a standardized place where incoming changes to the ATO, if applicable, go before merging to master.

Need to know what's up? Always go to repo-x, branch `authority-to-operate`.

Happy to discuss though if you have other ideas.

**Comment by khandelwal** [comment]
Interesting. I think there are two ways to think about this: 
1. That the ATO is part of the main repository. That's what happens when the SSP yaml file are included in the main branch. 
2. That the ATO is a branch thing. In the sense that not everybody who is going to use this open source code is going to care about the ATO. In which case, shouldn't the YAML files added stay in the branch and never be part of main? 

(This is a thought exercise)

**Comment by konklone** [comment]
> Need to know what's up? Always go to repo-x, branch authority-to-operate.
> 
> Happy to discuss though if you have other ideas.

I get the idea, though this is so against the grain of some folks' working habits (mine included) that it feels a bit fragile. I'm imagining people cleaning up branches and deleting it without thinking. The philosophy of git more generally is that branching is supposed to be "cheap" and ephemeral.

The existence of `system-security-plan.yml` seems like it might provide the necessary hook. Is there other metadata in the branch itself that's helpful or needed? The file's GitHub history would automatically tie it back to the PR that added it.

**Comment by khandelwal** [comment]
github.io pages use the gh-pages branch to publish content. So, perhaps not so ephemeral in the Github world?

**Comment by khandelwal** [comment]
Another thing to think about is the fact that an ATO is an artifact of this code's deployment - not of the code itself.

**Comment by NoahKunin** [comment]
@khandelwal the `18f-pages` or `gh-pages` model is exactly the one I was thinking about investigating here. The idea being that any commit to an `ato` branch re-generates the documentation that lives in a GitBook / 18F Guides page or whatever else we cook up in the future.

**Comment by NoahKunin** [comment]
Another alternative model we could explore is in the same way we have docs/issues-only/project management repos, the ATO docs start to live there instead to handle the branching clean-up issue.

However that cuts against my overall design imperative, which is that the long term solution to ATO timeline issues is to bring the process closer and closer and closer to the code base and infrastructure.

Interesting ideas to explore.

**Comment by NoahKunin** [comment]
Lastly, on the subject of many users of open-source don't care about ATOs, they do care (perhaps increasingly so) about security. That doesn't mean even the current or future state of the SSP YAML is the way to explain the security model of the thing they're thinking about using/forking, but it does lead me to believe there should be something in `master` for them to look at.

I guess that could also simply be a link in the readme file to somewhere, or even a simpler `security.md` file in line with `license.md`.

**Comment by konklone** [comment]
Generally (not always) the GH/18F Pages branch is the main branch of the repo, and cannot be deleted -- or would be so ingrained into the team that it would be unlikely to be.

I guess I just don't know why the answer can't be:

> Need to know what's up? Always go to repo-x, file `system-security-plan.yml`.

And I agree:

> but it does lead me to believe there should be something in `master` for them to look at.

I think that's also important for our fellow government employees, in helping them more easily discover our ATO/SSP workflow and import something like it back home.

**Pull request merged**
