### PR TITLE
Add some more self-service statistics

### PR DESCRIPTION
**Pull request by khandelwal**
We get requests for some of these numbers. Let's stop generating them on demand, and allow folks to see them themselves.

### CODE REVIEW

**Comment by OpenGlobe** [comment]
So this looks great - I'm wondering if we should add some additional "explanatory" text on how to use / interpret these numbers correctly?  It seems that a description of what they are (and certainly what they are not) might be helpful.

**Comment by khandelwal** [comment]
Yeah, I've been thinking that too. Let me see if I can add more clarity.

**Comment by OpenGlobe** [comment]
Just sent a pull request - use if you like, but might not be very user friendly.

**Comment by khandelwal** [comment]
This now includes @OpenGlobe changes. Merge if ok?

**Pull request merged**
